language: python

python:
  - "3.5"

sudo: enabled

install:
  - pip install codecov coverage
  - pip install -r Python/FunctionalDimensionality/requirements.txt

script:
  - make test

after_success:
  - cd Python/FunctionalDimensionality/; codecov
